### ISSUE TITLE
Unable to move icons

### ISSUE THREAD

**Issue by JarJarBlinkz** [Veticia/binaries#1] opened 2023-04-19 17:35 UTC
Currently i am unable to move Game icons to different tabs to categorize the content on my headset.

I am currently running the latest version of meta quest PTC v53 released today 04/19/23

**Comment by Veticia** [comment] 2023-04-25 21:13
Sorry for late reply, but I thought it was on a source code repo and couldn't see it when I actually wanted to reply.

Can you verify for me that the edit mode is turned on? Did it work before? Like on older firmware? Can you also check for me that it works on earlier piLauncherNext version or even original lvonasek's piLauncher?

Because I don't have quest and I cannot replicate it on pico. It works just fine here. While I don't really support quest I'd like to keep it working if issue was caused by a regression caused by my code.

**Comment by JarJarBlinkz** [comment] 2023-04-26 05:25
It has only stopped working since updating to android 12 it works fine on
previous firmware as i run it on 2 other headsets that are still on v50
firmware.

**Comment by JarJarBlinkz** [comment] 2023-04-26 05:32
Sorry i am running pilauncher last version released your launchernext and
bastis version, all are encountering the same issue everything works except
moving icons

**Comment by Veticia** [comment] 2023-04-26 15:32
Ah, I see. Probably some change in Android api then. I'll try to investigate but no promises.

**Comment by JarJarBlinkz** [comment] 2023-04-26 16:23
Highly appreciate it thank you again

**Comment by davidscode** [comment] 2023-04-28 02:04
I'm a Quest2 user.
I have been using it since August 2022.
I am experiencing the same problem as Johnr79.

Since the recent android update,
I can't drag and move icon to another tab.

I was originally using v0.5.5,
I had this problem, so I installed v1.0.2,
and I still have the same problem.

Please make the pi launcher available in quest2.

**Comment by Veticia** [comment] 2023-05-06 23:53
Duplicate of https://github.com/Veticia/PiLauncherNext/issues/4

**Closed as completed by Veticia** 2023-05-06 23:53 UTC
