### ISSUE TITLE
Can't move icons

### ISSUE THREAD

**Issue by davidscode** [Veticia/binaries#2] opened 2023-05-04 07:12 UTC
I'm a Quest2 user.
I have been using pi launcher since August 2022.
Thank you for making such a nice app.

But I've been having the same problem as Johnr79 for a while now.

Since the recent Android version update, 
I can't move icons to other tabs.
Specifically, I can't drag icons.

I was using v0.5.5 before, 
and after the issue, I tested v1.0.3, 
and I still have the same problem.

I would really appreciate, 
if you could make pi launcher available in quest2.

**Comment by Veticia** [comment] 2023-05-06 23:53
Duplicate of https://github.com/Veticia/PiLauncherNext/issues/4

**Closed as completed by Veticia** 2023-05-06 23:53 UTC
